Version = 0x287
[General]
OutputAPI =d3d11_fl11_0
Adapters = all
FullScreenOutput = default
FullScreenMode =true
ScalingMode =stretched_ar
ProgressiveScanlineOrder =true
EnumerateRefreshRates = false
Brightness =115
Color =100
Contrast =100
InheritColorProfileInFullScreenMode = true
KeepWindowAspectRatio = true
CaptureMouse = true
CenterAppWindow = true
DisableScreenSaver = true

[GeneralExt]
DesktopResolution = 
DesktopBitDepth = 
DeframerSize = 1
ImageScaleFactor = 1
CursorScaleFactor = 0
DisplayROI = 
Resampling =bicubic
PresentationModel = auto
ColorSpace = appdriven
WatermarkDisplayDuration = 0
FreeMouse = false
WindowedAttributes =fullscreensize 
FullscreenAttributes =fake 
FPSLimit = 0
Environment = 
SystemHookFlags = 

[Glide]
VideoCard = voodoo_2
OnboardRAM = 8
MemorySizeOfTMU = 4096
NumberOfTMUs = 2
TMUFiltering =appdriven
DisableMipmapping = false
Resolution =max_fhd
Antialiasing =2x
EnableGlideGammaRamp =false
ForceVerticalSync = true
ForceEmulatingTruePCIAccess = false
16BitDepthBuffer = false
3DfxWatermark = false
3DfxSplashScreen = false
PointcastPalette = false
EnableInactiveAppState = false

[GlideExt]
DitheringEffect =pure32bit
Dithering =disabled
DitherOrderedMatrixSizeScale = 0

[DirectX]
DisableAndPassThru = false
VideoCard = internal3D
VRAM = 256
Filtering =appdriven
Mipmapping = appdriven
KeepFilterIfPointSampled =true
Resolution =max_fhd
Antialiasing =2x
AppControlledScreenMode =false
DisableAltEnterToToggleScreenMode =false
Bilinear2DOperations =false
PhongShadingWhenPossible = false
ForceVerticalSync = true
dgVoodooWatermark = false
FastVideoMemoryAccess = false
DisableD3DTnLDevice = false

[DirectXExt]
AdapterIDType = 
VendorID = 
DeviceID = 
SubsystemID = 
RevisionID = 
DefaultEnumeratedResolutions = all
ExtraEnumeratedResolutions = 1280x720, 1920x1080, 2560x1440, 3840x2160
EnumeratedResolutionBitdepths = all
DitheringEffect =pure32bit
Dithering =disabled
DitherOrderedMatrixSizeScale = 0
DepthBuffersBitDepth = appdriven
Default3DRenderFormat = auto
MaxVSConstRegisters = 256
D3D12BoundsChecking = true
AlternativeScaling = false
NPatchTesselationLevel = 0
DisplayOutputEnableMask = 0xffffffff
MSD3DDeviceNames = false
RTTexturesForceScaleAndMSAA = true
SmoothedDepthSampling = true
DeferredScreenModeSwitch = false
PrimarySurfaceBatchedUpdate = false
SuppressAMDBlacklist = false

[Debug]
Info = enable
Warning = enable
Error = enable
MaxTraceLevel = 0

